blank_issues_enabled: false
contact_links:
  - name: Questions and Discussions
    url: https://github.com/cjmlarson/outlook-mcp/discussions
    about: Please ask and answer questions in the discussions section